### ISSUE TITLE
New release tag

### ISSUE THREAD

**Issue by neochief** [GeSHi/geshi-1.0#106]
It would be awesome if you could create a new release tag so that the lastest 7.2 fixes would be accessible from the composer.

**Comment by BenBE** [comment]
Will need to do some cleanup. Cannot guarantee any schedule yet.

**Comment by mizunashi-mana** [comment]
@BenBE Could you release only with https://github.com/GeSHi/geshi-1.0/pull/100 as minor patch release for 1.0.9 ?

Now, PHP team provide no active support for PHP 7.1, and PHP 7.2 is the main version with active support: https://secure.php.net/supported-versions.php .

**Comment by ywarnier** [comment]
I agree with @mizunashi-mana. Just a minor new version with just that patch would be enough. We want to include GeSHi features in the https://github.com/chamilo/chamilo-lms software but cannot depend on a moving master branch in our dependencies... (in the worst case we would need to fork and tag just for that, but it would be much better if we had a release with it from the original project as we don't intend on maintaining a fork ourselves)

**Comment by Amstutz** [comment]
Bump and +1.

**Comment by Mistralys** [comment]
Bump, +1.

A release to fix at least the deprectated message would be very appreciated.

**Comment by StudioMaX** [comment]
@cweiske and @BenBE sorry for ping, can you do something with this?

**Comment by splitbrain** [comment]
@cweiske @BenBE can we please have a version bump?

Maybe it's time to open access to this repository to more contributors?

**Comment by BenBE** [comment]
Fixed by https://github.com/GeSHi/geshi-1.0/releases/tag/v1.0.9.1
