### ISSUE TITLE
Deprecated: Function create_function() is deprecated

### ISSUE THREAD

**Issue by Neurozone** [GeSHi/geshi-1.0#126]
Deprecated: Function create_function() is deprecated in /var/www/tld/vendor/geshi/geshi/src/geshi.php on line 4698

**Comment by mermshaus** [comment]
Has been fixed in [ed9f49a](https://github.com/GeSHi/geshi-1.0/commit/ed9f49a7c7a195f6ed2bc864f5ce03b990b5867d). There isn’t a release with the fix, yet.
