### ISSUE TITLE
Go highlighting borks on numbers

### ISSUE THREAD

**Issue by fasterit** [GeSHi/geshi-1.0#149]
**GeSHi v1.0.9.1**

From our effort to revive Stikked (as in the pastebin):

> A PHP Error was encountered
> 
> Severity: Warning
> 
> Message: Undefined array key 1
> 
> Filename: geshi/geshi.php
> 
> Line Number: 3490
> 
> Backtrace:
> 
> File: /var/www/stikked/application/libraries/geshi/geshi.php
> Line: 3490

Repoducer:
```bash
$ echo "Test1" > test
$ php geshi-cli.php -f go test
PHP Warning:  Undefined array key 1 in /magic/geshi/geshi.php on line 3490
PHP Warning:  Undefined array key 2 in /magic/geshi/geshi.php on line 3490
<pre class="go" style="font-family:monospace;">Test1
&nbsp;</pre>

$ sed -n '3489,3491p' geshi.php 
                if (!$this->use_classes) {
                    $attributes = ' style="' . $this->language_data['STYLES']['NUMBERS'][$id] . '"';
                } else {

```
Greetings,
/DLange

**Comment by BenBE** [comment]
That's a bug in the Go language file.

Fix is simply to provide proper styles for those number formats too:

```diff
$ git diff
diff --git a/src/geshi/go.php b/src/geshi/go.php
index 83d3cabc..b48f8431 100644
--- a/src/geshi/go.php
+++ b/src/geshi/go.php
@@ -324,7 +324,9 @@ $language_data = array(
             0 => 'color: #cc66cc;' // FIXME: Duplicate array key
             ),
         'NUMBERS' => array(
-            0 => 'color: #cc66cc;'
+            0 => 'color: #cc66cc;',
+            1 => 'color: #cc66cc;',
+            2 => 'color: #cc66cc;'
             ),
         'METHODS' => array(
             0 => 'color: #004000;'
```

As documented a bit further up in the file, 0 is integers, 1 is floating point numbers, 2 is for imaginary number literals.

With the patch as is, this formats all three the same; though depending on what is needed, slight differences for these colors may be worth to use.

**Comment by fasterit** [comment]
Thank you @BenBE . Applied as https://github.com/fasterit/stikked-fit/commit/ba8e410b3e20c4001cd49e537dd27acb5296b391

**Comment by BenBE** [comment]
Applied in 7884d222
