### ISSUE TITLE
Lua block comment totally broken

### ISSUE THREAD

**Issue by hartman** [GeSHi/geshi-1.0#32]
We updated MediaWiki to the latest version of Geshi last week, but now all Multiline comment blocks in the Lua language no longer close.

Examples:
- https://en.wikipedia.org/wiki/Module:String
- https://en.wikipedia.org/wiki/Module:Citation/CS1

**Comment by splitbrain** [comment]
This should be fixed with the merge of #63 and can be closed I believe.
