### ISSUE TITLE
methods in R S+ code (rsplus) result in funny HTML-related additions instead of producing a hyperlink

### ISSUE THREAD

**Issue by molecules** [GeSHi/geshi-1.0#36]
Thank you so much for your work on GeSHi!

I just came across a bug. I tried this at http://qbnz.com/highlighter/demo.php, and it worked the same way it does in DokuWiki (where I originally noticed it):

In R S+ code,  anything using a <em>method</em> results in funny text that looks like the end of a URL (which seems to be related to creating a link to the documentation):

seed <- new ()

results in 

seed <- methods/html/new.html">new()

**Comment by Klap-in** [comment]
Trying with Scilab code shows an similar issue:

```
for n=[1,2,5,10,20,50,100]
    plot2d([-1.5,-1/n,1/n,1.5],[0,0,1,1],2+floor(2*log(n)))
end
```
becomes:
```
scilab.org/product/dic-mat-sci/M2SCI_doc.htm">for n=[1,2,5,10,20,50,100]
    plot2d([-1.5,-1/n,1/n,1.5],[0,0,1,1],2+floor(2*log(n)))
scilab.org/product/dic-mat-sci/M2SCI_doc.htm">end
```

**Comment by BenBE** [comment]
@Klap-in Please open a separate issue for Scilab so it can be traced independently. TIA.
