### ISSUE TITLE
PHP7 Support

### ISSUE THREAD

**Issue by archfrog** [GeSHi/geshi-1.0#59]
Hi,

I just migrated a few sites using GeSHi v1.0.8.11 to PHP7.  There was only one change:

  (geshi.php 597) "GeSHi" -> "__construct" as PHP7 requires constructors to be named "__construct".

So far, I haven't seen any other issues with GeSHi v1.0.8.11 and PHP7 and I've tested it for a few days.

Cheers,
Archfrog

**Comment by markseu** [comment]
Looks like there is a pull request https://github.com/GeSHi/geshi-1.0/pull/60 - would be great to get it merged. :+1:

**Comment by BenBE** [comment]
Merged.
