### ISSUE TITLE
geshi.org, qbnz.com not available - 502 bad gateway

### ISSUE THREAD

**Issue by peterdd** [GeSHi/geshi-1.0#68]
@BenBE join forces with https://github.com/easybook/geshi ?

I do not know which of the two I should support with fixes, Some fix that issue and the other fork fixes other issues ...

**Comment by peterdd** [comment]
websites seems to be working again.

But no response yet about the 'join' ..

**Comment by mermshaus** [comment]
There’s some discussion on the topic in #62.
