### ISSUE TITLE
You fixes the vulnerability?

### ISSUE THREAD

**Issue by jenokizm** [GeSHi/geshi-1.0#74]
hi! for geshi I found a variety of reports about vulnerabilities. Say they have already been fixed in this repository? By commits could not keep track of fixes(
https://vulners.com/search?query=geshi

**Comment by cweiske** [comment]
commit deb74a7d5cf9b510c27c3d421a1e7c994ddce53f fixed it:

```
Author: Benny Baumann <benbe@geshi.org>
Date:   Sat Jun 23 22:36:42 2012 +0000

    fix: Work around remote directory traversal and information disclosure bug
```
