### ISSUE TITLE
enable_line_number method causes division by zero error

### ISSUE THREAD

**Issue by okkakii** [GeSHi/geshi-1.0#90]
I think enable_line_number method  should receive a number greater than 0  in param $nth_row.
When the method receive 0 ( param $nth_row) ,   causes division by zero error.

If I use this method wrong,   would you tell me the correct way.

**Comment by cweiske** [comment]
The second parameter `$nth_row` is described as:

> For fancy line numbers, the second parameter is used to signal which lines are to be fancy. For example, if the value of this parameter is 5 then every 5th line will be fancy.

Making every 0th line fancy is ... wrong :)

If you think that geshi should check if it is greater than 0, please provide a patch.
