### ISSUE TITLE
php 7 incompatible compatibility

### ISSUE THREAD

**Issue by jenokizm** [GeSHi/geshi-1.0#94]
# critical
#### src\geshi\php-brief.php
* newOperatorWithReference
 * Line 18: ` *  -  Fixed &new problem`

#### src\geshi\php.php
* newOperatorWithReference
 * Line 18: ` *  -  Fixed &new problem`

#### src\geshi\rebol.php
* newOperatorWithReference
 * Line 18: ` *  -  Fixed &new problem`

# nuance
#### src\geshi.php
* funcGetArg
 * Line 3336: `        $arrays = func_get_args();`

**Comment by mermshaus** [comment]
Please explain this further, @jenokizm. It looks a bit spammy because you are listing syntax problems in source code comments. :slightly_smiling_face:

**Comment by cweiske** [comment]
Geshi is PHP7-compatible, see http://qbnz.com/highlighter/news.php?id=135

**Comment by jenokizm** [comment]
Using func_get_arg()/func_get_args() after modifying a parameter passed to a function will now return the modified value. You are right, this need not be fixed. : Slightly_smiling_face:  We will consider this report as my joke. I think your day has become a little more fun. Correctly that have closed.
